### ISSUE TITLE
Radio doesn't seem to take into account Frequency

### ISSUE THREAD

**Issue by Windyo** [dbuezas/esphome-cc1101#12]
I bought a radio that was recommended as working for 303Mhz despite being listed at 404 originally.

Further to our other issue I did a few tests far away from another other noise, but the radio picks up nothing at all in the 300Mhz range, despite listing the frequency.

I do, however, get correct signals when doing tests at the 404Mhz range, even if the frequency si set up to be 303. I'm not sure if this is expected or if it indicates that the radio is not in fact using the frequency I specified.

**Comment by dbuezas** [comment]
This works fine for me
