### ISSUE TITLE
Multical 21 watermeter (danish brand) 

### ISSUE THREAD

**Issue by jascdk** [dbuezas/esphome-cc1101#23]
Hi :) om using this code https://github.com/chester4444/esp-multical21 for getting values from my water meter . Would the cc1101 code you have made to be able to do the same as in the repo above ?

**Comment by dbuezas** [comment]
The repo you linked implements a specific protocol, it is not compatible with esphome's remote_receiver/transmitter (which can only detect and send specific codes)

**Comment by jascdk** [comment]
ahhh ok - thanks:)
