### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by FreelandA** [dbuezas/esphome-cc1101#27]
When I try to compile my project, I get multiple reds and yellow warnings and errors.
Ive attached the logs from the compile and my yaml file.

[logs_fan-controller_compile.txt](https://github.com/dbuezas/esphome-cc1101/files/15031649/logs_fan-controller_compile.txt)
[fan-controller censored.txt](https://github.com/dbuezas/esphome-cc1101/files/15031660/fan-controller.censored.txt)

**Comment by dbuezas** [comment]
follow the example yaml files and make sure to copy the h file
