### ISSUE TITLE
Need support to create YAML configuration to read water meter data and send it to HA

### ISSUE THREAD

**Issue by smartmatic** [dbuezas/esphome-cc1101#5]
Hi,

i found this Github Repo and i hope you can help me. I am using a cc1101 433 MHz to read the data from my water meter which is working. I figured out the exact frequency. What is not working is to send the data to HA via MQTT. Unfortunately the developer is no longer supporting the project in order to support.

This is the project: https://github.com/psykokwak-com/everblu-meters-esp8266

Therefore i searched after a ESPhome solution but i am really struggling to create the YAML file.
My question is if somebody can create a YAML file for me as i dont know how and where to start?

I would really appreciate your support!

**Comment by dbuezas** [comment]
This is not a simple task, the device sends real data and not only a limited number of specific patterns.
I'd recommend you try to get mqtt to work instead.
Wish you luck!
