### ISSUE TITLE
cannot transmit or receive

### ISSUE THREAD

**Issue by deanfourie1** [dbuezas/esphome-cc1101#8]
I am still unable to get this to work.

I've shifted over to a Wemos ESP WROOM02 D1 Battery Shield and using the same code, I get a log message saying that the remote code was sent but nothing received.

On my receiver, I do seem to be getting a lot of noise, so I take it its receiving ok?? But still, no sign of the code received and no trigger on the garage output.

One other thing, with the stock YAML, same code but one on a WemosD1 mini and one on the Wemos D1 Battery Sheild, however I do not get any of the noise on the WROOM02 shield as I do on the D1mini.

Any ideas?
Thanks

Pic of the noise I receive

<img width="1069" alt="image" src="https://github.com/dbuezas/esphome-cc1101/assets/71812804/953fe3f0-7cd3-49dc-9773-c2e3aad7d96b">

**Comment by dbuezas** [comment]
do you have a the frequency setup, on a matching antenna and board? 
there are 2 versions of the cc1101 boards: one is optimized for 868 and the other to 432 Mhz.

Regarding the noise, it could be that the battery shield has less noise on 3.3v rail and that that results in less noise (maybe)

Are you using the exact same gpios as in the yaml in this repo? not all gpios are created equal in the esp8266

**Comment by deanfourie1** [comment]
Thanks for the reply.

Yes, It has D1 to D8 labelled. So wired identically to the D1mini.

I bought 4 of these units, so I have 2 of them setup, with the same antennas etc, one wired to the D1 battery Shield and one to the D1 mini.

Thanks

**Comment by deanfourie1** [comment]
This is the guy I got so i'm guessing 433.

<img width="228" alt="image" src="https://github.com/dbuezas/esphome-cc1101/assets/71812804/ab79e8c1-fb6f-4b99-bb34-ca9a1753b598">

**Comment by dbuezas** [comment]
Can you double check that your YAML matches all pins from here: https://github.com/dbuezas/esphome-cc1101/blob/main/cc1101.yaml

And also that your connections are on the right pins in the cc1101 and esp board

**Comment by deanfourie1** [comment]
to be fair, i have tripple checked. I'll have another look but 99% sure its not wiring,

Thanks

**Comment by dbuezas** [comment]
Worth also checking that vcc and gnd weren't forgotten,  or you accidentally looked at a pinout from below or something silly like that. I've lost weeks with simple issues of this nature: 😅

**Comment by deanfourie1** [comment]
Ok i've gone over wiring again tonight, it's definitely not the wiring.

**Comment by dbuezas** [comment]
Then I'm out of ideas. Pictures?

**Comment by deanfourie1** [comment]
Sure, here are pics of both transmitter and receiver.

Let me know if you want closer shots.


![20230528_224612.jpg](https://github.com/dbuezas/esphome-cc1101/assets/71812804/730cc210-987a-465e-8ea4-03eefeca8282)

![20230528_224604.jpg](https://github.com/dbuezas/esphome-cc1101/assets/71812804/0dc3ffa0-1a7d-4b13-b2cb-7ec16f23111e)
